[package]
name = "iroha_client"
version = "2.0.0-pre-rc.7"
authors = ["Iroha 2 team <https://github.com/orgs/soramitsu/teams/iroha2>"]
edition = "2021"
description = "Iroha Client is a Rust Library which encapsulates network related logic and gives users an ability to interact with Iroha Peers like they are non-distributed application."
readme = "README.md"
homepage = "https://github.com/hyperledger/iroha/tree/iroha2-dev"
repository = "https://github.com/hyperledger/iroha/tree/iroha2-dev"
license = "Apache-2.0"
keywords = ["crypto", "blockchain", "ledger", "iroha", "client"]
categories = ["cryptography::cryptocurrencies", "api-bindings"]

[badges]
is-it-maintained-issue-resolution = { repository = "https://github.com/hyperledger/iroha" }
is-it-maintained-open-issues = { repository = "https://github.com/hyperledger/iroha" }
maintenance = { status = "actively-developed" }

[dependencies]
iroha_config = { version = "=2.0.0-pre-rc.7", path = "../config" }
iroha_crypto = { version = "=2.0.0-pre-rc.7", path = "../crypto"}
iroha_data_model = { version = "=2.0.0-pre-rc.7", path = "../data_model", features = ["warp"] }
iroha_primitives = { version = "=2.0.0-pre-rc.7", path = "../primitives" }
iroha_logger = { version = "=2.0.0-pre-rc.7", path = "../logger"}
iroha_telemetry = { version ="=2.0.0-pre-rc.7", path = "../telemetry" }
iroha_version = { version = "=2.0.0-pre-rc.7", path = "../version" }
iroha_core = { version = "=2.0.0-pre-rc.7", path = "../core", features = ["dev-telemetry", "telemetry"]}

attohttpc = "0.22.0"
eyre = "0.6.8"
http = "0.2.8"
rand = "0.8.5"
serde = { version = "1.0.142", features = ["derive"] }
serde_json = "1.0.83"
tungstenite = "0.16"
base64 = "0.13.0"
thiserror = "1.0.32"
derive_more = "0.99.17"
parity-scale-codec = { version = "3.1.5", default-features = false, features = ["derive"] }


[dev-dependencies]
iroha_permissions_validators = { version = "=2.0.0-pre-rc.7", path = "../permissions_validators" }
iroha = { path = "../cli", features = ["dev-telemetry", "telemetry"] }

test_network = { version = "=2.0.0-pre-rc.7", path = "../core/test_network" }
tokio = { version = "1.20.1", features = ["rt", "rt-multi-thread"] }
criterion = { version = "0.3.6", features = ["html_reports"] }
color-eyre = "0.6.2"
tempfile = "3.3.0"
hex = "0.4.3"

tracing-subscriber = { version = "0.3.15", default-features = false, features = ["fmt", "ansi"] }
tracing-flame = "0.2.0"

[[bench]]
name = "torii"
harness = false

[[bench]]
name = "tps-dev"
harness = false
path = "benches/tps/dev.rs"

[[example]]
name = "tps-oneshot"
harness = false
path = "benches/tps/oneshot.rs"
