[workspace]
members = [
  "actor",
  "actor/derive",
  "cli",
  "client",
  "client_cli",
  "config",
  "config/derive",
  "core",
  "core/docs",
  "core/test_network",
  "crypto",
  "crypto_cli",
  "data_model",
  "futures",
  "futures/derive",
  "logger",
  "macro",
  "macro/derive",
  "p2p",
  "permissions_validators",
  "schema",
  "schema/bin",
  "schema/derive",
  "substrate",
  "telemetry",
  "tools/kura_inspector",
  "version",
  "version/derive",
]
