[package]
name = "iroha_executor_derive"

version.workspace = true
authors.workspace = true
edition.workspace = true

license.workspace = true

[lints]
workspace = true


[lib]
proc-macro = true

[dependencies]
iroha_macro_utils = { workspace = true }
iroha_data_model.workspace = true

syn = { workspace = true, features = ["full", "derive"] }
quote = { workspace = true }
proc-macro2 = { workspace = true }
manyhow = { workspace = true }
darling = { workspace = true }
