[package]
name = "iroha_p2p"
version = "2.0.0-pre-rc.7"
authors = ["Iroha 2 team <https://github.com/orgs/soramitsu/teams/iroha2>"]
edition = "2021"
homepage = "https://github.com/hyperledger/iroha/tree/iroha2-dev"
repository = "https://github.com/hyperledger/iroha/tree/iroha2-dev"
license = "Apache-2.0"
keywords = ["crypto", "blockchain", "ledger", "iroha"]
categories = ["cryptography::cryptocurrencies", "network-programming"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iroha_logger = { version = "=2.0.0-pre-rc.7", path = "../logger" }
iroha_crypto = { version = "=2.0.0-pre-rc.7", path = "../crypto" }
iroha_actor = { version = "=2.0.0-pre-rc.7", path = "../actor" }
iroha_macro = { version = "=2.0.0-pre-rc.7", path = "../macro" }
iroha_data_model = { version = "=2.0.0-pre-rc.7", path = "../data_model" }
iroha_data_model_derive = { version = "=2.0.0-pre-rc.7", path = "../data_model/derive" }

rand = "0.8.5"
tokio = { version = "1.20.1", features = ["rt-multi-thread", "macros"] }
async-stream = "0.3.3"
futures = { version = "0.3.21", default-features = false }
async-trait = "0.1.57"
parity-scale-codec = { version = "3.1.5", features = ["derive"] }
aead = "0.5.1"
thiserror = "1.0.32"
derive_more = "0.99.17"

[dev-dependencies]
iroha_config = { version = "=2.0.0-pre-rc.7", path = "../config" }
test_network = { version = "=2.0.0-pre-rc.7", path = "../core/test_network" }
