[package]
name = "iroha_telemetry"
version = "2.0.0-pre-rc.7"
authors = ["Iroha 2 team <https://github.com/orgs/soramitsu/teams/iroha2>"]
edition = "2021"
build = "build.rs"

[features]
# Support developer-specific telemetry.
# Should not be enabled on production builds.
dev-telemetry = []
# Export Prometheus metrics. See https://prometheus.io/.
metric-instrumentation = []

[dependencies]
iroha_config = { version = "=2.0.0-pre-rc.7", path = "../config" }
iroha_logger = { version = "=2.0.0-pre-rc.7", path = "../logger" }
iroha_futures = { version = "=2.0.0-pre-rc.7", path = "../futures", features = ["telemetry"] }
iroha_telemetry_derive = { version = "=2.0.0-pre-rc.7", path = "derive" }


async-trait = "0.1.57"
chrono = "0.4.22"
eyre = "0.6.8"
futures = { version = "0.3.21", default-features = false, features = ["std", "async-await"] }
serde_json = "1.0.83"
streaming-stats = "0.2.3"
serde = { version = "1.0.142", features = ["derive"] }
tokio = { version = "1.20.1", features = ["rt", "rt-multi-thread", "macros"] }
tokio-stream = { version = "0.1.9", features = ["fs"] }
tokio-tungstenite = "0.17.2"
url = { version = "2.2.2", features = ["serde"] }
prometheus = { version = "0.13.1", default-features = false }


[build-dependencies]
anyhow = "1.0.60"
vergen = { version = "7.3.2", default-features = false, features = ["cargo", "git"] }
