[package]
name = "parity_scale_decoder"

edition.workspace = true
version.workspace = true
authors.workspace = true

license.workspace = true

[lints]
workspace = true

[features]
# Disable colour for all program output.
# Useful for Docker-based deployment and terminals without colour support.
no-color = ["colored/no-color"]

[dependencies]
iroha_data_model = { workspace = true, features = ["http"] }
iroha_primitives = { workspace = true }
iroha_schema = { workspace = true }
iroha_schema_gen = { workspace = true }
iroha_crypto = { workspace = true }
iroha_version = { workspace = true }
iroha_genesis = { workspace = true }
iroha_sample_params = { workspace = true }

clap = { workspace = true, features = ["derive", "cargo"] }
eyre = { workspace = true }
parity-scale-codec = { workspace = true }
colored = "2.0.4"

[build-dependencies]
iroha_data_model = { workspace = true }

parity-scale-codec = { workspace = true }
serde_json = { workspace = true, features = ["std"]}
serde = { workspace = true }
eyre = { workspace = true }
