name: I2::Base::Publish

on:
  workflow_dispatch:
  push:
    branches:
      - iroha2-dev
      - iroha2-stable
      - iroha2-lts
    paths:
      - "Dockerfile.base"

jobs:
  tag:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: [dev, stable, lts]
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - id: tag
        if: github.ref == 'refs/heads/iroha2-${{ matrix.tag }}'
        run: echo "::set-output name=tag::${{ matrix.tag }}"

  dockerhub:
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push iroha2-base:${{ needs.tag.outputs.tag }} image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: hyperledger/iroha2-base:${{ needs.tag.outputs.tag }}
          file: Dockerfile.base
