name: I2::Dev::Static Analysis

on:
  pull_request:
    branches: [iroha2-dev]
    paths:
      - "**.rs"
      - "**.json"
      - "**.toml"
      - ".github/workflows/**.yml"

      # Not part of the workspace
      - "!wasm/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: 7272721/i2-ci:nightly
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2

      - name: Format check
        run: cargo +nightly-2022-08-15 fmt --all -- --check
      - name: Lints without features
        run: cargo +nightly-2022-08-15 lints clippy --workspace --benches --tests --examples --quiet --no-default-features
        if: always()
      - name: Lints with all features enabled
        run: cargo +nightly-2022-08-15 lints clippy --workspace --benches --tests --examples --quiet --all-features
        if: always()
      - name: no_std compatibility check
        run: cargo nono check --package iroha_data_model --no-default-features
        if: always()
      - name: Documentation check
        run: if cargo doc -q 2>&1 | grep '^'; then exit 1; fi
        if: always()
