name: I2::Dev::Title

on:
  pull_request_target:
    branches: [iroha2-dev]
    types: [opened, edited, reopened]

jobs:
  check_to_label:
    runs-on: ubuntu-latest
    steps:
      - id: feature-match
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ github.event.pull_request.title }}
          regex: '^\[feature\] #\d+(, #\d+)*: .+$'
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ steps.feature-match.outputs.match != '' }}
        with:
          github_token: ${{ secrets.github_token }}
          labels: |
            Enhancement
        continue-on-error: true

      - id: refactor-match
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ github.event.pull_request.title }}
          regex: '^\[refactor\]( #\d+(, #\d+)*)?: .+$'
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ steps.refactor-match.outputs.match != '' }}
        with:
          github_token: ${{ secrets.github_token }}
          labels: |
            Refactor
        continue-on-error: true

      - id: fix-match
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ github.event.pull_request.title }}
          regex: '^\[fix\] #\d+(, #\d+)*: .+$'
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ steps.fix-match.outputs.match != '' }}
        with:
          github_token: ${{ secrets.github_token }}
          labels: |
            Bug
        continue-on-error: true

      - id: docs-match
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ github.event.pull_request.title }}
          regex: '^\[documentation\]( #\d+(, #\d+)*)?: .+$'
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ steps.docs-match.outputs.match != '' }}
        with:
          github_token: ${{ secrets.github_token }}
          labels: |
            Documentation
        continue-on-error: true

      - id: ci-match
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ github.event.pull_request.title }}
          regex: '^\[ci\]( #\d+(, #\d+)*)?: .+$'
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ steps.ci-match.outputs.match != '' }}
        with:
          github_token: ${{ secrets.github_token }}
          labels: |
            CI
        continue-on-error: true

      - name: Mismatch
        if: ${{ steps.fix-match.outputs.match == '' && steps.refactor-match.outputs.match == '' && steps.feature-match.outputs.match == '' && steps.docs-match.outputs.match == '' && steps.ci-match.outputs.match == '' }}
        run: exit 1
