name: I2::Dev::Title

on:
  pull_request:
    branches: [iroha2-dev]
    types: [opened, edited, reopened]

jobs:
  match:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     category: [ci, documentation, feature, fix, refactor]
        # include:
        #   - category: ci
        #     label: CI
        #   - category: ci
        #     regex: '^\[ci\]( #\d+(, #\d+)*)?: .+$'
        #   - category: documentation
        #     label: Documentation
        #   - category: documentation
        #     regex: '^\[documentation\]( #\d+(, #\d+)*)?: .+$'
        #   - category: feature
        #     label: Enhancement
        #   - category: feature
        #     regex: '^\[feature\] #\d+(, #\d+)*: .+$'
        #   - category: fix
        #     label: Bug
        #   - category: fix
        #     regex: '^\[fix\] #\d+(, #\d+)*: .+$'
        #   - category: refactor
        #     label: Refactor
        #   - category: refactor
        #     regex: '^\[refactor\]( #\d+(, #\d+)*)?: .+$'
    # outputs:
    #   is_match: ${{ steps.match_result.outputs.is_match }}
    #   label: ${{ matrix.label }}
    steps:
      - name: Category match
        id: ${{ matrix.category }}-match
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ github.event.pull_request.title }}
          regex: '^\[ci\]( #\d+(, #\d+)*)?: .+$'
      # - id: match_result
      #   if: steps.${{ matrix.category }}-match.outputs.match != ''
      #   run: ｜
      #     echo "::set-output name=is_match::true"

  label:
    # needs: match
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        # if: needs.match.outputs.is_match
        with:
          github_token: ${{ secrets.github_token }}
          labels: |
            CI
            # ${{ needs.match.outputs.label }}

  assert_valid:
    # needs: match
    runs-on: ubuntu-latest
    steps:
      - name: Assert
        # if: ! needs.match.outputs.is_match
        if: false == 'false'
        run: exit 1
