name: I2::Label

on:
  pull_request_target:
    branches: [iroha2-dev, iroha2-stable, iroha2-lts]
    types: [opened]

jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.github_token }}
          labels: |
            iroha2
