name: I2::Dev::Publish

on:
  push:
    branches: [test/change_detection]

env:
  CARGO_TERM_COLOR: always

# Note jobs in this workflow are run on `push` meaning that there's
# no point in burning our AWS self-hosted runners' time. Hence
# `ubuntu-latest` and not `[self-hosted, Linux]`.
jobs:
  dockerhub:
    runs-on: ubuntu-latest
    container:
      image: 7272721/i2-ci:nightly
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: dorny/paths-filter@v2.10.2
        id: filter
        with:
          filters: |
            base-image:
              - 'Dockerfile.base'
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push iroha2-base image
        if: steps.filter.outputs.base-image == 'true'
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: s8sato/iroha2-base:dev
          labels: commit=${{ github.sha }}
          file: Dockerfile.base
      - name: Build and push iroha2:dev image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: s8sato/iroha2:dev
          labels: commit=${{ github.sha }}
          build-args: TAG=dev
