name: I2::Dev::Static

on:
  pull_request:
    branches: [iroha2-dev]
    paths:
      - "**.rs"
      - "**.json"
      - "**.toml"
      - ".github/workflows/**.yml"

      # Not part of the workspace
      - "!wasm/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analysis:
    runs-on: ubuntu-latest
    container:
      image: 7272721/i2-ci:nightly
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2

      - name: Format
        run: cargo +nightly-2022-08-15 fmt --all -- --check
      - name: Lints without features
        if: always()
        run: cargo +nightly-2022-08-15 lints clippy --workspace --benches --tests --examples --quiet --no-default-features
      - name: Lints with all features enabled
        if: always()
        run: cargo +nightly-2022-08-15 lints clippy --workspace --benches --tests --examples --quiet --all-features
      - name: Documentation without features
        if: always()
        run: cargo +nightly-2022-08-15 doc --no-deps --quiet --no-default-features
      - name: Documentation with all features enabled
        if: always()
        run: cargo +nightly-2022-08-15 doc --no-deps --quiet --all-features
      - name: no_std compatibility
        if: always()
        run: cargo nono check --package iroha_data_model --no-default-features
