name: I2::Base::Publish

on:
  workflow_call:

jobs:
  dockerhub:
    strategy:
      matrix:
        tag: [dev, stable, lts]
    if: github.ref == 'refs/heads/iroha2-${{ matrix.tag }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push iroha2-base:${{ matrix.tag }} image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: hyperledger/iroha2-base:${{ matrix.tag }}
          context: .
          file: Dockerfile.base
