name: I2::Release::Publish

on:
  push:
    branches: [iroha2-stable, iroha2-lts]

env:
  CARGO_TERM_COLOR: always

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    container:
      image: 7272721/i2-ci:nightly
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: tj-actions/changed-files@v29.0.2
        id: changed-files
      - name: Get tag from branch name
        run: |
          BRANCH=${{ github.ref_name }}
          PREFIX='iroha2-'
          TAG=${BRANCH#$PREFIX}
          echo "TAG=$TAG" >>$GITHUB_ENV
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push iroha2-base image
        if: contains(steps.changed-files.outputs.modified_files, 'Dockerfile.base')
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: hyperledger/iroha2-base:${{ env.TAG }}
          labels: commit=${{ github.sha }}
          file: Dockerfile.base
      - name: Build and push iroha2 image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: hyperledger/iroha2:${{ env.TAG }}
          labels: commit=${{ github.sha }}
          build-args: TAG=${{ env.TAG }}

  load-rs:
    runs-on: ubuntu-latest
    container:
      image: 7272721/i2-ci:nightly
    steps:
      - name: Get tag from branch name
        run: |
          BRANCH=${{ github.ref_name }}
          PREFIX='iroha2-'
          TAG=${BRANCH#$PREFIX}
          echo "TAG=$TAG" >>$GITHUB_ENV
      - name: Build and push docker image (load-rs:release)
        run: |
          sleep 10s
          echo "wait to finish other workflow"
      - uses: convictional/trigger-workflow-and-wait@v1.6.2
        with:
          owner: soramitsu
          repo: iroha2-longevity-load-rs
          github_token: ${{ secrets.G_ACCESS_TOKEN }}
          workflow_file_name: load-rs-push-from-${{ env.TAG }}.yaml
          ref: iroha2-${{ env.TAG }}
