name: I2::Dev::Bench

on:
  pull_request:
    branches: [iroha2-dev]
    paths:
      - "**.rs"
      - "**.toml"
      - "**.yml"

      # Not part of the workspace
      - "!wasm/**"

env:
  CARGO_TERM_COLOR: always
  RUSTC_BOOTSTRAP: 1

jobs:
  bench:
    runs-on: [self-hosted, Linux]
    container:
      image: 7272721/i2-ci:latest
    steps:
      # WIP
      # Check out the dev branch
      # Build and benchmark to establish a baseline
      # Switch to the pull request branch
      # Build and benchmark to compare against the baseline
