name: I2::Release::Deploy

on:
  push:
    branches: [iroha2]

env:
  CARGO_TERM_COLOR: always
  RUSTC_BOOTSTRAP: 1

jobs:
  coverage:
    runs-on: ubuntu-latest
    container:
      image: 7272721/i2-ci:latest
    steps:
      - uses: actions/checkout@v2

      # Should be done in `7272721/i2-ci`
      - name: Add component
        run: rustup component add llvm-tools-preview
      - name: Install cargo-llvm-cov
        run: cargo install cargo-llvm-cov

      - name: Generate code coverage
        run: mold --run cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@v2
        with:
          files: lcov.info
          fail_ci_if_error: true


  deploy:
    runs-on: ubuntu-latest
    container:
      image: 7272721/i2-ci:latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - name: set up buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Iroha Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: hyperledger/iroha2:stable
          build-args: |
            TARGET_DIR=release
            PROFILE=--release
      - name: Build and push Iroha client cli Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: hyperledger/iroha2:client-cli-stable
          build-args: |
            TARGET_DIR=release
            PROFILE=--release
            BIN=iroha_client_cli
      - name: Build and push Iroha Crypto CLI Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: hyperledger/iroha2:kagami-stable
          build-args: |
            TARGET_DIR=release
            PROFILE=--release
            BIN=kagami

      - name: Build and push load-rs:release docker image
        run: |
          sleep 10s
          echo "wait to finish other workflow"
      - uses: convictional/trigger-workflow-and-wait@v1.6.0
        with:
          owner: soramitsu
          repo: iroha2-longevity-load-rs
          github_token: ${{ secrets.G_ACCESS_TOKEN }}
          workflow_file_name: load-rs-push-from-release.yaml
          ref: release
