name: Check PR Title

on:
  pull_request:
    branches: [iroha2-dev]
    types: [opened, edited, reopened]

jobs:
  check_pr_title:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-regex-match@v2
        id: feature-match
        with:
          text: ${{ github.event.pull_request.title }}
          regex: '^\[(feature|feat\.?)\] \#?([[:digit:]]+|\(([[:digit:]]+,?\s?)+\)):.+$'

      - uses: actions-ecosystem/action-regex-match@v2
        id: refactor-match
        if: ${{ steps.feature-match.outputs.match == '' }}
        with:
          text: ${{ github.event.pull_request.title }}
          regex: '^\[ref(actor)?\]( \#?([[:digit:]]+|\(([[:digit:]]+,?\s?)+\)):)?.+$'

      - uses: actions-ecosystem/action-regex-match@v2
        id: fix-match
        if: ${{ steps.refactor-match.outputs.match == '' }}
        with:
          text: ${{ github.event.pull_request.title }}
          regex: '^\[(bug)?fix(up)?\] \#?([[:digit:]]+|\(([[:digit:]]+,?\s?)+\)):.+$'

      - name: Failure
        if: ${{ steps.fix-match.outputs.match == ''}}
        run: exit 1
