name: I2::Base::Publish

on:
  workflow_dispatch:
  push:
    branches:
      - test/workflow_run/base
    paths:
      - "Dockerfile.base"

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    container:
      image: 7272721/i2-ci:nightly
    steps:
      - uses: actions/checkout@v3
      - name: Get tag from branch name
        run: |
          BRANCH=${{ github.ref_name }}
          PREFIX='iroha2-'
          TAG=${BRANCH#$PREFIX}
          echo "TAG=$TAG" >>$GITHUB_ENV
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
