name: I2::Dev::Static Analysis

on:
  pull_request:
    branches: [iroha2-dev]
    paths:
      - "**.rs"
      - "**.json"
      - "**.toml"
      - "**.yml"

jobs:
  check:
    runs-on: [self-hosted, Linux]
    container:
      image: 7272721/i2-ci:latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ${{ env.CARGO_HOME }}
            target/
          key: iroha2-rust-check-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            iroha2-rust-check
      - name: Print all info
        run: |
          cargo version
          lscpu
          free -h
      - name: Format check
        run: cargo +nightly-2021-10-22 fmt --all -- --check
      - name: Static analysis without features
        run: cargo lints clippy --workspace --benches --tests --quiet
        if: always()
      - name: Static analysis with all features enabled
        run: cargo lints clippy --workspace --benches --tests --all-features --quiet
        if: always()
      - name: Documentation check
        run: |
          cargo doc --no-deps --quiet
          ./scripts/check_docs.sh
        if: always()
