name: I2::Dev::Nightly::Publish

on: workflow_dispatch

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push iroha2:dev-nightly image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: hyperledger/iroha2:dev-nightly-${{ github.sha }}
          labels: commit=${{ github.sha }}
          build-args: TAG=dev
