name: Add Iroha2 label

on:
  pull_request:
    branches: [iroha2-dev, iroha2]
    types: [opened, edited, reopened]

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.github_token }}
          labels: |
            iroha2
