name: I2::Dev::Tests

on:
  pull_request:
    branches: [iroha2-dev]
    paths:
      - "**.rs"
      - "**.json"
      - "**.toml"
      - ".github/workflows/**.yml"

      # Not part of the workspace
      - "!wasm/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  checks:
    runs-on: ubuntu-latest
    container:
      image: 7272721/i2-ci:nightly
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Check config.md
        if: always()
        run: ./scripts/check.sh docs
      - name: Check genesis.json
        if: always()
        run: ./scripts/check.sh genesis
      - name: Wasm build check
        if: always()
        working-directory: wasm
        run: mold --run cargo +nightly-2022-08-15 build --target wasm32-unknown-unknown --quiet

  with_coverage:
    runs-on: [self-hosted, Linux]
    container:
      image: 7272721/i2-ci:nightly
    strategy:
      matrix:
        feature_flag: [all-features, no-default-features]
    steps:
      - uses: actions/checkout@v3
      # TODO Remove this step #2165
      - name: Add components to nightly channel
        run: rustup component add llvm-tools-preview --toolchain nightly-2022-08-15-x86_64-unknown-linux-gnu
      - uses: Swatinem/rust-cache@v2
      - name: Run tests, with ${{ matrix.feature_flag }}
        run: |
          mold --run cargo llvm-cov clean --workspace
          mold --run cargo +nightly-2022-08-15 llvm-cov --doc --no-report --${{ matrix.feature_flag }} --workspace --no-fail-fast
          mold --run cargo llvm-cov --no-report --${{ matrix.feature_flag }} --workspace --no-fail-fast
      - name: Generate lcov report
        if: matrix.feature_flag == 'all-features'
        run: |
          # generate report without tests
          # https://github.com/taiki-e/cargo-llvm-cov#merge-coverages-generated-under-different-test-conditions
          mold --run cargo +nightly-2022-08-15 llvm-cov --no-run --${{ matrix.feature_flag }} --workspace --doctests --lcov --output-path lcov.info
      - name: Upload coverage to codecov.io
        if: matrix.feature_flag == 'all-features'
        uses: codecov/codecov-action@v3
        with:
          files: lcov.info
          fail_ci_if_error: true
      - name: Upload codecov report artifact
        uses: actions/upload-artifact@v3
        with:
          name: lcov-${{ github.event.pull_request.head.sha }}.info
          path: lcov.info

  integration:
    runs-on: ubuntu-latest
    container:
      image: 7272721/i2-ci:nightly
    timeout-minutes: 60
    strategy:
      matrix:
        feature_flag: [all-features, no-default-features]
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Run tests, with ${{ matrix.feature_flag }}
        run: |
          mold --run cargo test --test mod --${{ matrix.feature_flag }} -- \
          integration:: --skip unstable_network
