name: I2::Dev::Tests (Unstable)

on:
  pull_request:
    branches: [iroha2-dev]
    paths:
      - "**.rs"
      - "**.json"
      - "**.toml"
      - "**.yml"

      # Not part of the workspace
      - "!wasm/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: [self-hosted, Linux]
    container:
      image: 7272721/i2-ci:latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - name: Run tests
        run: mold --run cargo test -p iroha_client --tests unstable_network --quiet
