name: I2::Base::Publish

on:
  workflow_dispatch:
  push:
    branches:
      - iroha2-dev
      - iroha2-stable
      - iroha2-lts
    paths:
      - "Dockerfile.base"

jobs:
  dockerhub:
    strategy:
      matrix:
        tag: [dev, stable, lts]
    if: github.ref == 'refs/heads/iroha2-${{ matrix.tag }}'
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push iroha2-base:${{ matrix.tag }} image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: hyperledger/iroha2-base:${{ matrix.tag }}
          labels: commit=${{ github.sha }}
          file: Dockerfile.base
