name: I2::Dev::Tests (Unstable)

on:
  pull_request:
    branches: [iroha2-dev]
    paths:
      - "**.rs"
      - "**.json"
      - "**.toml"
      - "**.yml"

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: [self-hosted, Linux]
    container:
      image: 7272721/i2-ci:latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ${{ env.CARGO_HOME }}
            target/
          key: iroha2-rust-test-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            iroha2-rust-test
      - name: Run tests
        run: cargo test -p iroha_client --tests unstable_network --quiet
