name: I2::Dev::Tests (Unstable)

on:
  pull_request:
    branches: [iroha2-dev]
    paths:
      - "**.rs"
      - "**.json"
      - "**.toml"
      - ".github/workflows/**.yml"

      # Not part of the workspace
      - "!wasm/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: [self-hosted, Linux]
    container:
      image: 7272721/i2-ci:nightly
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: mold --run cargo +nightly-2022-08-15 test -p iroha_client --tests unstable_network --quiet
