name: I2::Release::Publish

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  dockerhub:
    runs-on: [self-hosted, Linux]
    container:
      image: 7272721/i2-ci:nightly
    strategy:
      matrix:
        tag: [stable, lts]
    if: github.ref == 'refs/heads/iroha2-${{ matrix.tag }}'
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push iroha2:${{ matrix.tag }} image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: hyperledger/iroha2:${{ matrix.tag }}
          context: .
          file: Dockerfile
          build-args: TAG=${{ matrix.tag }}

      - name: Build and push docker image (load-rs:release)
        run: |
          sleep 10s
          echo "wait to finish other workflow"
      - uses: convictional/trigger-workflow-and-wait@v1.6.2
        with:
          owner: soramitsu
          repo: iroha2-longevity-load-rs
          github_token: ${{ secrets.G_ACCESS_TOKEN }}
          workflow_file_name: load-rs-push-from-${{ matrix.tag }}.yaml
          ref: iroha2-${{ matrix.tag }}
