name: I2::Release::Deploy

on:
  push:
    branches: [iroha2]

env:
  CARGO_TERM_COLOR: always
  RUSTC_BOOTSTRAP: 1

jobs:
  # Coverage is both in PR and in push pipelines so that:
  # 1. PR can get coverage report from bot.
  # 2. Coverage bot can have results from
  # `iroha2-dev` to report coverage changes.
  coverage:
    runs-on: ubuntu-latest
    container:
      image: 7272721/i2-ci:latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - name: Run tests
        run: |
          mold --run cargo +nightly-2022-04-20 test \
          --quiet --workspace --no-fail-fast -- \
          --skip unstable_network --skip ui --test-threads 3
        env:
          RUSTFLAGS: "-C instrument-coverage"
          LLVM_PROFILE_FILE: "iroha-%p-%m.profraw"
      - name: Generate a grcov coverage report
        run: |
          grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info
        if: always()
      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@v2
        if: always()
        with:
          file: lcov.info


  deploy:
    runs-on: ubuntu-latest
    container:
      image: 7272721/i2-ci:latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - name: set up buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Iroha Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: hyperledger/iroha2:stable
          build-args: |
            TARGET_DIR=release
            PROFILE=--release
      - name: Build and push Iroha client cli Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: hyperledger/iroha2:client-cli-stable
          build-args: |
            TARGET_DIR=release
            PROFILE=--release
            BIN=iroha_client_cli
      - name: Build and push Iroha Crypto CLI Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: hyperledger/iroha2:kagami-stable
          build-args: |
            TARGET_DIR=release
            PROFILE=--release
            BIN=kagami

      - name: Build and push load-rs:release docker image
        run: |
          sleep 10s
          echo "wait to finish other workflow"
      - uses: convictional/trigger-workflow-and-wait@v1.6.0
        with:
          owner: soramitsu
          repo: iroha2-longevity-load-rs
          github_token: ${{ secrets.G_ACCESS_TOKEN }}
          workflow_file_name: load-rs-push-from-release.yaml
          ref: release
