name: I2::Release::Tests

# on:
#   pull_request:
#     branches: [iroha2]
on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  cli-test:
    runs-on: [self-hosted, linux]
    container:
      image: 7272721/i2-ci:latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - name: Build Client CLI
        run: mold -run cargo build
        working-directory: client_cli
      - name: Build Iroha Peer
        run: mold -run cargo build
        working-directory: cli
      - name: Mark both binaries as executable
        run: |
          chmod +x target/debug/iroha
          chmod +x target/debug/iroha_client_cli
      - name: Setup test environment
        run: bash -c './scripts/test_env.sh setup'
      - name: Genesis test
        run: bash -c './scripts/tests/genesis.sh || (cat test/peers/iroha0.log; false )'
      - name: Basic register and mint
        run: bash -c './scripts/tests/register_mint_quantity.sh || (cat test/peers/iroha0.log; false )'
        if: always()
      - name: Cleanup test environment
        run: bash -c './scripts/test_env.sh cleanup'

# Omitted below
